Repository UNopenGIS/foil4g, pull requests merged in 2024-07, with the labels that each got.

#95 Add Smart Maps Global Elevation Tiles data source
  lib/data/data.source.coop/smartmaps/gel/index.yaml
Labels: add data, by copilot

#97 Implement Smart Maps GEL Map component
  src/components/Datasets/GEL/index.stories.ts
  src/components/Datasets/GEL/index.tsx
  src/components/Datasets/GEL/source.ts
Labels: enhancement, by copilot

#100 Update VientianeLandusePMTilesSource URL to use new data source
  src/components/Datasets/VientianeLanduse/source.ts
Labels: enhancement

#106 Update index.tsx - change map center
  src/components/Datasets/GoogleOpenBuildings/index.tsx
Labels: enhancement

#107 refactor: import map as `MapComponent`
  src/components/Datasets/ArmedConflict/index.stories.ts
  src/components/Datasets/DEM1A/index.stories.ts
  src/components/Datasets/GEL/index.stories.ts
  src/components/Datasets/OpenCellId/index.stories.ts
  src/components/Datasets/OvertureMaps/index.stories.ts
  src/components/Datasets/Rwanda10/index.stories.ts
  src/components/Datasets/VientianeLanduse/index.stories.ts
  src/components/Maps/OpenStreetMap/OpenStreetMapFrHotRaster/index.stories.ts
  src/components/Maps/OpenStreetMap/OpenStreetMapJpOSMBrightVector/index.stories.ts
  src/components/Maps/OpenStreetMap/OpenStreetMapOrgRaster/index.stories.ts
  src/components/Maps/SatelliteImagery/ArcGISWorldImagery/index.stories.ts
  src/components/Maps/SatelliteImagery/GSISeamlessPhoto/index.stories.ts
  src/components/Maps/UNClearMapRaster/index.stories.ts
Labels: refactoring
